[en]
  title = "Bridge Public Schools"
  LanguageName = "English"
  weight = 1

[es]
  title = "Bridge Public Schools"
  LanguageName = "Español"
  weight = 2
  [es.params]
    introDescription = "Demostrando lo posible. Cada niño. Rumbo a la universidad."
